# Generated by Django 3.2.5 on 2021-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_image',
            field=models.CharField(max_length=100),
        ),
    ]
