# Generated by Django 3.2.5 on 2021-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0002_alter_post_posted_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
