# Generated by Django 3.2.5 on 2021-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0003_alter_post_posted_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
