# Generated by Django 3.2.5 on 2021-09-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0007_auto_20210920_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
