# Generated by Django 3.2.5 on 2021-09-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0012_alter_comment_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
