# Generated by Django 3.2.5 on 2021-10-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
