# Generated by Django 3.2.5 on 2007-12-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
