# Generated by Django 3.2.8 on 2021-10-16 12:10

from django.db import migrations, models
import userinfoapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfoapi', '0004_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=userinfoapi.models.upload_to, verbose_name='Image'),
        ),
    ]
